### ISSUE TITLE
RPC Server is unavailable (0x800706BA)

### ISSUE THREAD

**Issue by platanus-kr** [alxnbl/onenote-md-exporter#5]
![20210125-PW-001-232327](https://user-images.githubusercontent.com/6806008/105721469-f284ed00-5f67-11eb-814a-4ef1ce7e85a0.png)

OS: Windows 10 Pro 20H2 19042.746
Onenote : OneNote 2016 

The same is true even if you run it with administrator privileges.
Notes are not returned.

**Comment by alxnbl** [comment]
Hi Platanus, 
Do you have 32 or 64 bit version of Office ? 
Are you running OneNoteMdExport from binary release or from source code in Visual Studio ?
Is OneNote started before running export and are you interacting with OneNote during export ?

**Comment by platanus-kr** [comment]
Dear.
This is a 64-bit office.
I used version [0.2 binary](https://github.com/alxnbl/onenote-md-exporter/releases/tag/v0.2) .
When the list of notes on the command line is displayed, OneNote does not run with a form indicating that the note is damaged. (One note is normally executed after the comment line ends.)
And it prints the same error as the first screenshot of the issue.

Additionally, when I try with OneNote for Windows 10 (UWP), it doesn't even load the note list.

Thank you.

**Comment by alxnbl** [comment]
Thanks for the details. Surprising, does the error append with a specific notebook or all ones ?
Can you try to close all your notebooks and create a dummy notebook and see if it continues to produce the error ? It will helps to determine if error is relative to your computer setup or your notebook contents.

About OneNote for Windows 10 (UWP), It's not supported by the tool because I don't think it provides Office Interop APIs. I will add this point in the tool limitations.

**Comment by platanus-kr** [comment]
![20210126-PW-001-094852](https://user-images.githubusercontent.com/6806008/105784465-37d30a00-5fbc-11eb-9d1e-a491282007f2.png)
P is new dummy note.

Unfortunately, I closed all the notes and tried creating a new dummy, but it doesn't work.
However, unlike before, a message indicating that the export was successful is displayed. But the content doesn't exist.

**Comment by alxnbl** [comment]
Seams that the issue is specific to your configuration... Can you join the dummy notebook you have created (.one file) and the "consoleapp.log" log file that should be next to OneNoteMdExporter exec.
If you have access to an other computer running office, It would be interesting to import your notes and try to export them from it.

**Comment by alxnbl** [comment]
I published a new release (0.2.1) that add more logs. Maybe it can give us more information to help finding the origin of your error.

**Comment by platanus-kr** [comment]
Long time no see.

I've converted your notes with your version 0.3.1.
However, I recommend that you clearly state the following information in the user manual.

1. Before executing Exporter, OneNote must be running.
2. Exporter must be run with normal user rights. I kept trying with admin rights.

I finally escape from One Note due to your Exporter.
Thank you.

**Comment by alxnbl** [comment]
Thank you for the comment. I added in version 0.5.0 a screen at software start-up that list all the requirements of the tool.
