### ISSUE TITLE
Avoid corrupted pages to bloc the export of the rest of the notebook

### ISSUE THREAD

**Issue by alxnbl** [alxnbl/onenote-md-exporter#75]
Currently, after processing a corrupted page of a Notebook, OneNote crash and then all following pages processed by the tool are on error.

**Comment by alxnbl** [comment]
Solved in version 1.3.0

**Comment by davidyang** [comment]
Hey @alxnbl - I'm getting an error where on a certain notebook it's immediately crashing (no pages are listed or being exported).

I've tried:

- Deleting all page history, disabling page history, Empty Recycle Bin

I get an error on line 167 but the contents of the Exception are from line 170 (GetPageContent).  Is it possible that there's newer code that isn't in the 1.3.0 release?  I'm in the process of trying to build from git and will report back if I'm able to complete that process.

**Comment by alxnbl** [comment]
Thanks for the report, if your able to join a copy of your notebook i will try to investigate.

**Comment by davidyang** [comment]
Hey @alxnbl - any advice on getting it to build?  I'm getting this error: 


Error | MSB3091 | Task failed because "AxImp.exe" was not found, or the correct Microsoft Windows SDK is not installed. The task is looking for "AxImp.exe" in the "bin" subdirectory beneath the location specified in the InstallationFolder value of the registry key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\NETFXSDK\4.8\WinSDK-NetFx40Tools-x86. You may be able to solve the problem by doing one of the following:  1) Install the Microsoft Windows SDK.  2) Install Visual Studio 2010.  3) Manually set the above registry key to the correct location.  4) Pass the correct location into the "ToolPath" parameter of the task. | OneNoteMdExporter | C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets | 2977 |  

I've installed the Windows SDK - but I'm using VS 2022 - do I need to be on 2019?

**Comment by davidyang** [comment]
I added a console.writeline before line 170 in OneNoteExtensions so I can see what file was causing issues.  Perhaps if the debug flag is on we can output that so it's easy to delete notes that are causing issues?

Also, I had to install Visual Studio 2019 (with the Office SDK selected, perhaps VS 2022 would have worked if I had selected that option).

I also had to change TargetFramework to net5.0 to compile - even though I had dotnet 6 installed, not sure why that is for me.
