### ISSUE TITLE
Support faster speed

### ISSUE THREAD

**Issue by laerhu** [alxnbl/onenote-md-exporter#77]
Thank you so much for your great work!
It's very easy to use and has a very high accuracy and helped me a lot.

Describe

Need acceleration with options like high cpu utilization and hyper-thread optimization etc.

Detail

My Onenote has 1k notes whose markdown have about 5k files and 0.5GB of space.
The 2 PCs each took 40 mins and 70 mins to do the export. The process is a bit slow while the cpu is more idle.
The new cpu (6c12t) is only 30% faster than the old (2c4t) despite a 80% higher cpubenchmark score.

<details>
<summary>cpu utilization screenshot</summary>

<img src="https://user-images.githubusercontent.com/26965450/204704756-8366cdb6-6cec-4763-9467-70d630093c34.png" height="240">

<img src="https://user-images.githubusercontent.com/26965450/204704789-3aba0cd2-404f-4436-99a1-e9c38d6be08b.png" height="240">

</details>

**Comment by alxnbl** [comment]
Hey @laerhu, thank you for your feedback. 99% of the execution time of the export is spend during the export operation of OneNote which can not be optimized because it is the code of MS. And indeed, this code is monothreaded and cannot profit of multi-core CPU architectures. You will need to be patient :).
